### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by mischa2002k2** [artemklevtsov/RGA#10]
Hi,
the code and everything works just fine. But if the token expires, my code is not working any more:

``` r
authorize(
  client.id=options()$apiSecrets$id, 
  client.secret=options()$apiSecrets$clientSecret,
  cache=paste(getwd(),"daToken",sep="/")
)
```

Message:

``` r
Error : client error: (401) Unauthorized
Auth error: Invalid Credentials
```

How can I make sure, the code will persist the token? I don't want to login every single time in my browser. Plus: after the token expires my whole code is not working any more. What is the desired practice on this point?

**Comment by artemklevtsov** [comment]
`RGA` uses `httr` package to make API requests. `Token2.0` object tries refresh token when it expired: https://github.com/hadley/httr/blob/f7593b7d5b3f9396469d1220dd4b38206fbb7d2e/R/request.R#L125..

``` r
token <- authorize(
    client.id = options()$apiSecrets$id, 
    client.secret = options()$apiSecrets$clientSecret,
    cache = paste(getwd(), "daToken", sep = "/")
)
token$cache_path
token$can_refresh()
token$refresh()
```

Do you sure that used the same credentials and cache path? Also check that credentials equals with the https://console.developers.google.com/project/_/apiui/credential.

**Comment by artemklevtsov** [comment]
I just tried to use successfully the old token:

``` r
list_profiles(token = authorize(cache = ".ga-token.rds"))
#> Auto-refreshing stale OAuth token.
#>           id account.id webproperty.id internal.webproperty.id                      name currency      timezone
```

So I can't reproduce your issue.

**Comment by mischa2002k2** [comment]
Ah, sorry, I'm not very experienced with R. So the best practice is to save the token variable as a local file and use `readRDS()` from file for use each time? Thanks.

**Comment by artemklevtsov** [comment]
Also it works with authorize():

``` r
> authorize(cache = ".ga-token.rds")
Access token will be stored in the '.ga-token.rds' file.
> list_profiles()
Auto-refreshing stale OAuth token.
```

**Comment by mischa2002k2** [comment]
Which is similar to my first attempt:

``` r
authorize(
  client.id=options()$apiSecrets$id, 
  client.secret=options()$apiSecrets$clientSecret,
  cache=paste(getwd(),"daToken",sep="/")
)
```

However the token is not working after some time.... because I set the token to a defined path value? (instead of default `.ga-token.rds`).

**Comment by artemklevtsov** [comment]
Can you try with default options?

**Comment by mischa2002k2** [comment]
If I run `authorize()` there is  no file `.ga-token.rds` created on my machine...  // sorry, now I found the error... I was sure the machine was showing hidden files, but it wasnt....

**Comment by artemklevtsov** [comment]
`.ga-token.rds` by default was created in the current working directory. This file is hidden by default. To get all files in the current dir type the following command:

``` r
list.files(getwd(), all.files = TRUE)
```

Expiration time is 3600 seconds. To get the expiration time:

``` r
library(httr)
library(RGA)
authorize()
content(GET(paste0("https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=", RGA:::.RGAEnv$Token$credentials$access_token)))
```

**Comment by mischa2002k2** [comment]
Hi Artem,
thanks for your effort and help, however I still can't figure out why I get the 401 unauthorized error. What is the desired way in RGA to write an application which won't make the user login every time?

If I use the command within 3600 sec it will give me proper result with a working token. After this time, the following happens:

``` r
content(GET(paste0("https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=", RGA:::.RGAEnv$Token$credentials$access_token)))
$error
[1] "invalid_token"

$error_description
[1] "Invalid Value"
```

I didn't change anything with the token file. I used this code to authorize:

``` r
authorize(client.id="", client.secret="",cache=paste(getwd(),"daToken",sep="/"))
```

The file `daToken` is found in the correct folder. I also checked for all default files and deleted them before I used "authorize". There is no other token then the one I see with the name `daToken` in the correct folder.

Whats wrong with my token?

Here is what I tried:
- delete the `daToken` file
- use: `authorize()` again, it will redirect me to my browser, after validation the script works fine
- within 3600 sec limit the command `content(GET(...))` will give me some info about my token (including the remaining time)
- after 3600 sec I get again the error posted above (invalid_token)

**Comment by artemklevtsov** [comment]
Can you test token obtained with the `httr::oauth2.0_token()`? Without RGA:

``` r
library(httr)
client.id <- "your key here"
client.secret <- "your secret here"
app <- oauth_app(appname = "app", key = client.id, secret = client.secret)
endpoint <- oauth_endpoints("google")
token <- oauth2.0_token(endpoint = endpoint, app = app, cache = FALSE,
                        scope = "https://www.googleapis.com/auth/analytics.readonly")
req <- GET(paste0("https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=",
                  token$credentials$access_token))
httr::content(req)
```

After 1 hour try reuse this token. If this works. Retry with `cache = TRUE`.

**Comment by mischa2002k2** [comment]
So it seems to be a problem with my token and `httr`? This is what I get when I try to use `httr::content(req)` after the token is expired:

``` r
$error
[1] "invalid_token"

$error_description
[1] "Invalid Value"
```

The code seems working, I can see the token object and a value in `access_token`. However the API responds with `invalid_token`. Not sure what I'm doing wrong...

**Comment by mischa2002k2** [comment]
After some research I think the problem is the missing "refresh_token". My token object has the following values:

``` r
token$credentials:
access_token, token_type, expires_in
```

But the "refresh_token" is missing. However in the `httr` package I just can't find the place to add the "access_type=offline" value, so the response has a refresh token. Where can I configure this part in `httr`?  (see http://stackoverflow.com/questions/8942340/get-refresh-token-google-api)

**Comment by artemklevtsov** [comment]
Check your application on the [Credentials page](https://console.developers.google.com/projectselector/apis/credentials). Type must be Other. Also verify Client ID and Client secret. Enable Analytics API on [this](https://console.developers.google.com/projectselector/apis/api/analytics/overview) page.

**Comment by mischa2002k2** [comment]
Hi Artem, you are correct, it was all just my fault. The project has two different logins.... I used the one with type not "other"... sorry to waste your time. Большое спасибо Артем!

**Comment by artemklevtsov** [comment]
Also you should close hadley/httr#314.
