### ISSUE TITLE
Support for service accounts in authorize()

### ISSUE THREAD

**Issue by m-stanley** [artemklevtsov/RGA#13]
Does RGA support/can it be amended to support [service accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) and private keys rather than user accounts and passwords in its credentials? I'm intending to use RGA to pull data from GA sometimes on a shiny server and using user accounts makes that process far more complicated.

Thanks!

**Comment by artemklevtsov** [comment]
Thank you for the suggestion.

Now you can use `httr::oauth_service_token()` to get the access token credentials. Then you can pass `TokenServiceAccount` object as token argument to the RGA functions.

In future I'll add option to choose type of the application.
