### ISSUE TITLE
Error: 'http_error' is not an exported object from 'namespace:httr'

### ISSUE THREAD

**Issue by jenccnej** [artemklevtsov/RGA#14]
Доброго времени суток!

Помогите пожалуйста решить проблему.

При выгрузке данных, получаю сначала ошибку:

> Error: 'http_error' is not an exported object from 'namespace:httr'

а потом при записи соответственно:

> Error in is.data.frame(x) : object 'ga_data' not found

Ссылку на скрин с кодом и ошибками - прилагаю: http://prntscr.com/9uobkk

**Comment by artemklevtsov** [comment]
Здравствуйте.

Используйте стабильную версию из CRAN. Версия из Git адаптирована для dev-версии `httr`.
Если по каким-то причинам Вам нужна git-версия, то откатите пакет до 3e4696a155318cbd4a50af9ec7716fe54d6aa884.

``` r
devtools::install_github("artemklevtsov/RGA@3e4696a")
```
