### ISSUE TITLE
Error: Receiving UseMethod("status_code") errors

### ISSUE THREAD

**Issue by ericbrownaustin** [artemklevtsov/RGA#16]
Getting no applicable method for 'status_code' applied to an object of class `NULL` errors after attempting `get_ga`, `get_realtime` or `list_profiles` functions.  I've tried reinstalls of both `RGA` and `httr` and still having issues.  I'm running v 0.3.2 of `RGA` and v 1.1.0 of `httr`.

``` r
> httr::with_verbose(list_profiles())
-> GET /analytics/v3/management/accounts/~all/webproperties/~all/profiles?start-index=1&max-results=1000 HTTP/1.1
-> Host: www.googleapis.com
-> User-Agent: libcurl/7.43.0 r-curl/0.9.5 httr/1.1.0
-> Accept-Encoding: gzip, deflate
-> Accept: application/json
-> Authorization: Bearer 
<- HTTP/1.1 200 OK
<- Expires: Tue, 02 Feb 2016 19:17:48 GMT
<- Date: Tue, 02 Feb 2016 19:17:48 GMT
<- Cache-Control: private, max-age=0, must-revalidate, no-transform
<- Vary: Origin
<- Vary: X-Origin
<- Content-Type: application/json; charset=UTF-8
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: SAMEORIGIN
<- X-XSS-Protection: 1; mode=block
<- Content-Length: 150766
<- Server: GSE
<- Alternate-Protocol: 443:quic,p=1
<- Alt-Svc: quic=":443"; ma=604800; v="30,29,28,27,26,25"
<- 
Error in UseMethod("status_code") : 
  no applicable method for 'status_code' applied to an object of class "NULL"
```

**Comment by artemklevtsov** [comment]
Thank you for the report. It's known issue and already fixed in the dev version (#12).

**Comment by ericbrownaustin** [comment]
I'm still getting the same error even after installing the dev version of `httr`.  It looks like `devtools` has `httr` as a dependency and Devtools is required for the dev install of `httr`.  I am not sure if that is causing an issue.

**Comment by artemklevtsov** [comment]
I mean dev version of the RGA package. Anyway today I submited the new version of the RGA on CRAN.
