### ISSUE TITLE
Error: token : cannot add bindings to a locked environment

### ISSUE THREAD

**Issue by diegocgaona** [artemklevtsov/RGA#18]
Hi,

I'm having the following error when I to authorize the token:

```
authorize(token = ga_token)
Error in tokens[[token$hash()]] <- token : cannot add bindings to a locked environment
```

If i use the interactive console, I try again and again and then, works. But I can't do with knitr...

I'm using R version 3.2.3 and RStudio Version 0.99.489.

Thanks!

**Comment by artemklevtsov** [comment]
But it works for me:

``````
---
output:
  md_document:
    variant: markdown_github
---

```{r}
ga_token <- readRDS(".ga-token.rds")[[1]]
library(RGA)
authorize(token = ga_token)
list_profiles()[[1]]
list_profiles(token = ga_token)[[1]]
```
``````

I tried render this file into RStuiod and with Rscript.

Please provide more info about the `ga_token` object and versions of the packages.

**Comment by diegocgaona** [comment]
Sorry, I had did some stupid thing...
I used: (in the real code I used my access keys)

``` r
ga_token <- authorize()
```

The, the ga_token was saved as a environment.
Now I did like you, and I read the RDS saved:

``` r
ga_token <- readRDS(".ga_token.rds")[[1]]
```

Now, worked fine.
Thanks!!!

**Comment by artemklevtsov** [comment]
``` r
> library(RGA)
> token <- authorize()
Access token will be stored in the '.ga-token.rds' file.
> authorize(token = token)
```

also works. Best practice is call `authorize()` with your own `cleint.id`, `client.secret` and `cache`.
