### ISSUE TITLE
Error: oauth_listener() needs an interactive environment.

### ISSUE THREAD

**Issue by chipoglesby** [artemklevtsov/RGA#20]
Hi @artemklevtsov, I'm trying to create a file that can be ran via cron job. It's basically just:

knitr::knit('report.Rmd').

When I run it in terminal, this is the error that I get:

> Client ID and Client secret loaded from environment variables.
> Access token will be stored in the '.ga-token.rds' file.
> Error: oauth_listener() needs an interactive environment.
> Execution halted

In the RMD file, I've called `library(RGA)` and authorize() and I've also tried `authorize(cache=TRUE, reauth=TRUE)` but I still get the error.

Do you have any ideas why this may be happening and how I can fix it?

Thank you.

**Comment by artemklevtsov** [comment]
Try the following steps:
- Authorize the RGA app in the interactive mode and cache token:

``` r
library(RGA)
authorize(client.id = " MyClientID", client.secret = "MyClientSecret", cache = "/projdir/ga-token")
```
- Authorize your app in the knitr doc with the cached token:

<pre>
---
title: "Untitled"
output: html_document
---
```{r}
library(RGA)
authorize(client.id = " MyClientID", client.secret = "MyClientSecret", cache = "/projdir/ga-token")
list_accounts()
 ```
</pre>

Note that when the OAuth token refreshed R-session rewrite the cache file. So you need write permissions for this file,
- Now we can knit the document.

<pre>
~ % Rscript -e 'knitr::knit("/tmp/test.Rmd")'                  :(
processing file: /tmp/test.Rmd
  |................................                                 |  50%
  ordinary text without R code
  |.................................................................| 100%
label: unnamed-chunk-1
output file: test.md
[1] "test.md"
</pre>

**Comment by chipoglesby** [comment]
Thank you, I'll try this now.

**Comment by chipoglesby** [comment]
This works. Thank you @artemklevtsov for your help!
