### ISSUE TITLE
Daily Limit Exceeded

### ISSUE THREAD

**Issue by flaviobrito** [artemklevtsov/RGA#39]
Hey There Artem,

I'm using it for many days without problem. But today after I did a simple query I received a message "daily limit exceeded". The curious is the project number returned isn't mine (console output).  If I try to follow the bellow link Google return to me another error. "You do not have sufficient permissions to view this page." 

Any idea?

My Limits are:

>  Queries
> requests per day  2 used of 50,000  
> requests per 100 seconds per user     900     

Console output

``` r
Batch processing mode enabled.
Fetch data by day: from 2015-01-01 to 2016-07-12.
  |                                                                                                                     |   0%
Error: Client error: (403) Forbidden
Daily limit exceeded: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/analytics/quotas?project=144394141628
```

Thanks
Flávio Brito

**Comment by artemklevtsov** [comment]
Hi. Try to use your own (other) Client ID and Client secret.

**Comment by flaviobrito** [comment]
Hey there Artem,
Thank you. It's ok today using my application credential not my web credential (used yesterday). Could be a proxy error?

**Comment by artemklevtsov** [comment]
Please read the docs: https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas#reporting_apis
