### ISSUE TITLE
get_unsampled_report() return a list?

### ISSUE THREAD

**Issue by meidata** [artemklevtsov/RGA#40]
Hi Artem again,

I am first using the `list_unsampled_reports` to get the id of the unsampled reports id like the following:

`unsample_List_Report <-list_unsampled_reports(ga_profiles$accountId,ga_profiles$webPropertyId,ga_profiles$id)`

![dddddddddddddd](https://cloud.githubusercontent.com/assets/15050769/16799200/dcc50e84-48ef-11e6-9f86-5c1354d51fb4.PNG)

And then i use the the id i got from above for the function `get_unsample_reports()`, but it return a list of summary information, not the dataset.

`visiteur_Meubles <- get_unsampled_report(ga_profiles$accountId,ga_profiles$webPropertyId,ga_profiles$id,unsample_List_Report$id[1],token = TokenGA)`

![und](https://cloud.githubusercontent.com/assets/15050769/16799184/d05f94d4-48ef-11e6-9b63-1829aeba7f59.PNG)

Is there anything i missed? 

Thank you in advance!!

**Comment by artemklevtsov** [comment]
`get_` methods always return a list (by design).
