### ISSUE TITLE
Error in BASH : oauth_listener() needs an interactive environment

### ISSUE THREAD

**Issue by AgnieszkaTomczyk** [artemklevtsov/RGA#50]
Hi @artemklevtsov :) :)
I'm trying to run some Rscript via cron job. 
The error I get in terminal is:

> Access token will be stored in the './ga-token.rds' file.
> Error: oauth_listener() needs an interactive environment.
> Execution halted

My code is:

```r
library(RGA)
authorize(client.id = ".......", client.secret = ".......", cache = "./ga-token.rds")`
```

Do you know what is wrong?
Thx,
Agnieszka

**Comment by artemklevtsov** [comment]
Hi @AgnieszkaTomczyk.

You should athuhorize the RGA app in interactive mode and store obtained credentials (cached by default). Then you can use a cached token in the non-interactive mode.

**Comment by AgnieszkaTomczyk** [comment]
Hi @artemklevtsov 
Thanks a lot. 
Would you be so kind and give me some more detailed instruction? 
I am a beginner in this field...

**Comment by artemklevtsov** [comment]
First look at #20.

**Comment by AgnieszkaTomczyk** [comment]
All right.
Thanks a lot.
A have just fixed it :)
