### ISSUE TITLE
get_realtime and filter ORGANIC

### ISSUE THREAD

**Issue by MarekLu** [artemklevtsov/RGA#60]
I found an issue in get_realtime function. I need to filter rt:medium ORGANIC results only:

```
d <- get_realtime(
  profileId = gaid,
  metrics = "rt:pageviews",
  dimensions = "rt:pageTitle",
  filters = "rt:medium==ORGANIC")
```

It ends with an erorr:

```
Error: Client error: (400) Bad Request
Invalid parameter: Invalid value 'rt:medium==,GANIC' for filters parameter.
```

Is there any way how to use ORGANIC (it must be in uppercase) in RGA?

**Comment by MarekLu** [comment]
There's a working workaround:

`rt:medium=~[O]RGANIC`

**Comment by artemklevtsov** [comment]
No related with RGA code.
